<script>try{$j=jQuery;Function.prototype.bind=function(obj){var that=this;return function(){return that.apply(obj,arguments);};};var Portal={};Portal.Bar=function(){var _instance=this;var _iRefreshCrossSellingPauseOnItems=9000;var _sExternalRef=null;var _eContainer=$j('#pbar');var _aIntervalIds={};var _aObservers={};var _bInitialized=false;var _bTickerInitialized=false;var _bVisible=true;this.EVNT_PB_SHOW='pbar.show';this.EVNT_PB_HIDE='pbar.hide';var _init=function(){_parseExternalRef();_build();};var _build=function(){_eContainer.find("#pb-tab-slide-open").hide();_eContainer.find("#pb-tab-slide-close").show();_eContainer.find("#pb-tab-slide-open").click(function(){$j("div.pb-outer").slideToggle("fast");_eraseCookie('pBarVisibility');_instance.trigger(_instance.EVNT_PB_SHOW);_bVisible=true;});_eContainer.find("#pb-tab-slide-close").click(function(){$j("div.pb-outer").slideUp("fast");_createCookie('pBarVisibility','hide',14);_instance.trigger(_instance.EVNT_PB_HIDE);_bVisible=false;});_eContainer.find(".pb-tab a").click(function(){$j(".pb-tab a").toggle();return false;});var sPBarVisibility=_readCookie('pBarVisibility');if(sPBarVisibility&&sPBarVisibility=='hide'){_eContainer.find('.pb-outer').hide();_eContainer.find('#pb-tab-slide-open').show();_eContainer.find('#pb-tab-slide-close').hide();_bVisible=false;}else{_eContainer.find('.pb-outer').show();_eContainer.find('#pb-tab-slide-open').hide();_eContainer.find('#pb-tab-slide-close').show();_bVisible=true;}
_eContainer.find('.pb-outer').show();_bVisible=true;_eContainer.find('.pb-moregames-overview li').hover(function(){$j(".pb-caption",this).stop().animate({top:'0px'},{queue:false,duration:160});},function(){$j(".pb-caption",this).stop().animate({top:'76px'},{queue:false,duration:160});});_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-overview-lists').toggle();_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-overview-lists').hover(function(){$j(this).show(50);},function(){$j(this).hide(50);});_eContainer.find(".pb-cntnt .pb-lang-sec .pb-lang-sec-options").toggle();_eContainer.find(".pb-cntnt .pb-lang-sec .pb-lang-sec-options").hover(function(){$j(this).show(50);},function(){$j(this).hide(50);});_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-overview-lists').hide();_eContainer.find('.pb-cntnt .pb-lang-sec .pb-lang-sec-options').hide();_eContainer.find('.pb-cntnt .pb-lang-sec .pb-lang-select').bind('click',function(){_eContainer.find(".pb-cntnt .pb-lang-sec .pb-lang-sec-options").toggle();_eContainer.find(".pb-cntnt .pb-lang-sec .pb-lang-sec-options").hover(function(){$j(this).show(50);},function(){$j(this).hide(50);});_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-overview-lists').hide();});_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-select').bind('click',function(){_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-overview-lists').toggle();_eContainer.find('.pb-cntnt .pb-moregames-sec .pb-moregames-overview-lists').hover(function(){$j(this).show(50);},function(){$j(this).hide(50);});_eContainer.find('.pb-cntnt .pb-lang-sec .pb-lang-sec-options').hide();});if(_sExternalRef!=null){var eIgLink=_eContainer.find('.pb-home a');var aFlags=_eContainer.find('.pb-lang-sec-options ul li a');var aGames=_eContainer.find('ul.pb-moregames-overview li a');var aCpFeeds=_eContainer.find('ul#pb-ticker-news li a');eIgLink.each(function(){_replaceRef($(this),_sExternalRef);});aFlags.each(function(){_replaceRef($(this),_sExternalRef);});aGames.each(function(){_replaceRef($(this),_sExternalRef);});aCpFeeds.each(function(){_replaceRef($(this),_sExternalRef);});}
var eTicker=_eContainer.find('.pb-sec-news .pb-news .pb-news-content ul#pb-ticker-news');if(eTicker.length>0){_eContainer.find('.pb-sec-news .pb-news').show();if(!_bTickerInitialized){eTicker.ticker({debugMode:true,titleText:'',displayType:'fade',pauseOnItems:_iRefreshCrossSellingPauseOnItems});_bTickerInitialized=true;}else{eTicker.unbind();eTicker.ticker({debugMode:true,titleText:'',displayType:'fade',pauseOnItems:_iRefreshCrossSellingPauseOnItems});}}};var _replaceRef=function(eAnker,sExternalRef){var sUrl=eAnker.attr('href');var sUrl=sUrl.replace(/ref=[\w_]+/,'ref='+sExternalRef);eAnker.attr('href',sUrl);}
var _parseExternalRef=function(){sQuery=document.location.search.substr(1,document.location.search.length);if(sQuery!=''){aKeysAndVals=sQuery.split('&');for(i=0;i<aKeysAndVals.length;++i){aKeyValTuple=aKeysAndVals[i].split('=');if(aKeyValTuple.length>1){if(aKeyValTuple[0]=='ref'){_sExternalRef=aKeyValTuple[1];break;}}}}};var _createCookie=function(sName,sValue,iDays){var sExpires="";if(iDays){var dDate=new Date();dDate.setTime(dDate.getTime()+(iDays*24*60*60*1000));sExpires="; expires="+dDate.toGMTString();}
document.cookie=sName+"="+sValue+sExpires+"; path=/";};var _readCookie=function(sName){var sNameEQ=sName+"=";var aPieces=document.cookie.split(';');for(var i=0;i<aPieces.length;i++){var sValue=aPieces[i];while(sValue.charAt(0)==' ')
sValue=sValue.substring(1,sValue.length);if(sValue.indexOf(sNameEQ)==0)
return sValue.substring(sNameEQ.length,sValue.length);}
return null;};var _eraseCookie=function(sName){_createCookie(sName,"",-1);};this.observe=function(sEventName,fCallback){if(!_aObservers[sEventName]){_aObservers[sEventName]=new Array();}
_aObservers[sEventName].push(fCallback);return fCallback;};this.unobserve=function(sEventName,fCallback){if(!_aObservers[sEventName]){return false;}
if(null==fCallback){_aObservers[sEventName]=[];}
var iIdx=$j.inArray(fCallback,_aObservers[sEventName]);if(iIdx<0){return false;}
_aObservers[sEventName].splice(iIdx,1);return true;};this.trigger=function(){var a=$j.makeArray(arguments);var sName=a.shift();if(!_aObservers[sName]){return;}
for(var i in _aObservers[sName]){_aObservers[sName][i].apply(undefined,a);}};this.isVisible=function(){return _bVisible;};this.run=function(){_init();};};(function($j){$j.fn.ticker=function(options){var opts=$j.extend({},$j.fn.ticker.defaults,options);var newsID='#'+$j(this).attr('id');var tagType=$j(this).get(0).tagName;return this.each(function(){var settings={position:0,time:0,distance:0,newsArr:{},play:true,paused:false,contentLoaded:false,dom:{contentID:'#pb-ticker-content',titleID:'#pb-ticker-title',titleElem:'#pb-ticker-title SPAN',tickerID:'#pb-ticker',wrapperID:'#pb-ticker-wrapper',revealID:'#pb-ticker-swipe',revealElem:'#pb-ticker-swipe SPAN',controlsID:'#pb-ticker-controls',prevID:'#pb-prev',nextID:'#pb-next',playPauseID:'#pb-play-pause'}};if(tagType!='UL'&&tagType!='OL'&&opts.htmlFeed===true){debugError('Cannot use <'+tagType.toLowerCase()+'> type of element for this plugin - must of type <ul> or <ol>');return false;}
opts.direction=='rtl'?opts.direction='right':opts.direction='left';initialisePage();function countSize(obj){var size=0,key;for(key in obj){if(obj.hasOwnProperty(key))size++;}
return size;};function debugError(obj){if(opts.debugMode){if(window.console&&window.console.log){window.console.log(obj);}
else{alert(obj);}}}
function initialisePage(){$j(settings.dom.wrapperID).append('<div id="'+settings.dom.tickerID.replace('#','')+'"><div id="'+settings.dom.titleID.replace('#','')+'"><span><!-- --></span></div><p id="'+settings.dom.contentID.replace('#','')+'"></p><div id="'+settings.dom.revealID.replace('#','')+'"><span><!-- --></span></div></div>');$j(settings.dom.wrapperID).removeClass('no-js').addClass('has-js '+opts.direction);$j(settings.dom.tickerElem+','+settings.dom.contentID).hide();if(opts.controls){$j(settings.dom.controlsID).live('click mouseover mousedown mouseout mouseup',function(e){var button=e.target.id;if(e.type=='click'){switch(button){case settings.dom.prevID.replace('#',''):settings.paused=true;$j(settings.dom.playPauseID).addClass('paused');manualChangeContent(button);break;case settings.dom.nextID.replace('#',''):settings.paused=true;$j(settings.dom.playPauseID).addClass('paused');manualChangeContent(button);break;case settings.dom.playPauseID.replace('#',''):if(settings.play==true){settings.paused=true;$j(settings.dom.playPauseID).addClass('paused');pauseTicker();}
else{settings.paused=false;$j(settings.dom.playPauseID).removeClass('paused');restartTicker();}
break;}}
else if(e.type=='mouseover'&&$j('#'+button).hasClass('controls')){$j('#'+button).addClass('over');}
else if(e.type=='mousedown'&&$j('#'+button).hasClass('controls')){$j('#'+button).addClass('down');}
else if(e.type=='mouseup'&&$j('#'+button).hasClass('controls')){$j('#'+button).removeClass('down');}
else if(e.type=='mouseout'&&$j('#'+button).hasClass('controls')){$j('#'+button).removeClass('over');}});$j(settings.dom.wrapperID).append('<ul id="'+settings.dom.controlsID.replace('#','')+'"><li id="'+settings.dom.playPauseID.replace('#','')+'" class="controls"></li><li id="'+settings.dom.prevID.replace('#','')+'" class="controls"></li><li id="'+settings.dom.nextID.replace('#','')+'" class="controls"></li></ul>');}
if(opts.displayType!='fade'){$j(settings.dom.contentID).mouseover(function(){if(settings.paused==false){pauseTicker();}}).mouseout(function(){if(settings.paused==false){restartTicker();}});}
processContent();}
function processContent(){if(settings.contentLoaded==false){if(opts.ajaxFeed){if(opts.feedType=='xml'){$j.ajax({url:opts.feedUrl,cache:false,dataType:opts.feedType,async:true,success:function(data){count=0;for(var a=0;a<data.childNodes.length;a++){if(data.childNodes[a].nodeName=='rss'){xmlContent=data.childNodes[a];}}
for(var i=0;i<xmlContent.childNodes.length;i++){if(xmlContent.childNodes[i].nodeName=='channel'){xmlChannel=xmlContent.childNodes[i];}}
for(var x=0;x<xmlChannel.childNodes.length;x++){if(xmlChannel.childNodes[x].nodeName=='item'){xmlItems=xmlChannel.childNodes[x];var title,link=false;for(var y=0;y<xmlItems.childNodes.length;y++){if(xmlItems.childNodes[y].nodeName=='title'){title=xmlItems.childNodes[y].lastChild.nodeValue;}
else if(xmlItems.childNodes[y].nodeName=='link'){link=xmlItems.childNodes[y].lastChild.nodeValue;}
if((title!==false&&title!='')&&link!==false){settings.newsArr['item-'+count]={type:opts.titleText,content:'<a href="'+link+'">'+title+'</a>'};count++;title=false;link=false;}}}}
if(countSize(settings.newsArr<1)){debugError('Couldn\'t find any content from the XML feed for the ticker to use!');return false;}
setupContentAndTriggerDisplay();settings.contentLoaded=true;}});}
else{debugError('Code Me!');}}
else if(opts.htmlFeed){if($j(newsID+' LI').length>0){$j(newsID+' LI').each(function(i){settings.newsArr['item-'+i]={type:opts.titleText,content:$j(this).html()};});setupContentAndTriggerDisplay();}
else{debugError('Couldn\'t find HTML any content for the ticker to use!');return false;}}
else{debugError('The ticker is set to not use any types of content! Check the settings for the ticker.');return false;}}}
function setupContentAndTriggerDisplay(){settings.contentLoaded=true;$j(settings.dom.titleElem).html(settings.newsArr['item-'+settings.position].type);$j(settings.dom.contentID).html(settings.newsArr['item-'+settings.position].content);if(settings.position==(countSize(settings.newsArr)-1)){settings.position=0;}
else{settings.position++;}
distance=$j(settings.dom.contentID).width();time=distance/opts.speed;revealContent();}
function revealContent(){$j(settings.dom.contentID).css('opacity','1');if(settings.play){var offset=$j(settings.dom.titleElem).width()+20;$j(settings.dom.revealID).css(opts.direction,offset+'px');if(opts.displayType=='fade'){$j(settings.dom.revealID).hide(0,function(){$j(settings.dom.contentID).css(opts.direction,offset+'px').fadeIn(opts.fadeInSpeed,postReveal);});}
else if(opts.displayType=='scroll'){}
else{$j(settings.dom.revealElem).show(0,function(){$j(settings.dom.contentID).css(opts.direction,offset+'px').show();animationAction=opts.direction=='right'?{marginRight:distance+'px'}:{marginLeft:distance+'px'};$j(settings.dom.revealID).css('margin-'+opts.direction,'0px').delay(20).animate(animationAction,time,'linear',postReveal);});}}
else{return false;}};function postReveal(){if(settings.play){$j(settings.dom.contentID).delay(opts.pauseOnItems).fadeOut(opts.fadeOutSpeed);if(opts.displayType=='fade'){$j(settings.dom.contentID).fadeOut(opts.fadeOutSpeed,function(){$j(settings.dom.wrapperID).find(settings.dom.revealElem+','+settings.dom.contentID).hide().end().find(settings.dom.tickerID+','+settings.dom.revealID).show().end().find(settings.dom.tickerID+','+settings.dom.revealID).removeAttr('style');setupContentAndTriggerDisplay();});}
else{$j(settings.dom.revealID).hide(0,function(){$j(settings.dom.contentID).fadeOut(opts.fadeOutSpeed,function(){$j(settings.dom.wrapperID).find(settings.dom.revealElem+','+settings.dom.contentID).hide().end().find(settings.dom.tickerID+','+settings.dom.revealID).show().end().find(settings.dom.tickerID+','+settings.dom.revealID).removeAttr('style');setupContentAndTriggerDisplay();});});}}
else{$j(settings.dom.revealElem).hide();}}
function pauseTicker(){settings.play=false;$j(settings.dom.tickerID+','+settings.dom.revealID+','+settings.dom.titleID+','+settings.dom.titleElem+','+settings.dom.revealElem+','+settings.dom.contentID).stop(true,true);$j(settings.dom.revealID+','+settings.dom.revealElem).hide();$j(settings.dom.wrapperID).find(settings.dom.titleID+','+settings.dom.titleElem).show().end().find(settings.dom.contentID).show();}
function restartTicker(){settings.play=true;settings.paused=false;postReveal();}
function manualChangeContent(direction){pauseTicker();switch(direction){case'prev':if(settings.position==0){settings.position=countSize(settings.newsArr)-2;}
else if(settings.position==1){settings.position=countSize(settings.newsArr)-1;}
else{settings.position=settings.position-2;}
$j(settings.dom.titleElem).html(settings.newsArr['item-'+settings.position].type);$j(settings.dom.contentID).html(settings.newsArr['item-'+settings.position].content);break;case'next':$j(settings.dom.titleElem).html(settings.newsArr['item-'+settings.position].type);$j(settings.dom.contentID).html(settings.newsArr['item-'+settings.position].content);break;}
if(settings.position==(countSize(settings.newsArr)-1)){settings.position=0;}
else{settings.position++;}}});};$j.fn.ticker.defaults={speed:0.10,ajaxFeed:false,feedUrl:'',feedType:'xml',displayType:'reveal',htmlFeed:true,debugMode:true,controls:false,titleText:'',direction:'ltr',pauseOnItems:3000,fadeInSpeed:600,fadeOutSpeed:300};})(jQuery);}catch(e){} $(function() { var pb = new Portal.Bar(); pb.run(); });</script>